spring:
  application:
    name: kafka-producer
server:
  port: 8282
kafka:
  bootstrapServers: localhost:9092,localhost:9093
  producer:
    topics: mytesttopic
okta:
  oauth2:
    issuer: https://{your-Okta-domain}/oauth2/default
    client-id: {your okta client-id}
    client-secret: {your okta client-secret}